name: Release
on:
  workflow_dispatch:
env:
  UV_PATH: "$HOME/.cargo/bin"
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check if running on main branch
        run: |
          if [[ "${{ github.ref }}" != "refs/heads/main" ]]; then
            echo "This workflow can only be run on the main branch"
            exit 1
          fi
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Cache uv
        id: cache-uv
        uses: actions/cache@v3
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-uv-${{ hashFiles('**/pyproject.toml') }}
      - name: Install uv
        if: steps.cache-uv.outputs.cache-hit != 'true'
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "${{ env.UV_PATH }}" >> $GITHUB_PATH
      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-python-${{ hashFiles('**/pyproject.toml') }}
      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          export PATH="${{ env.UV_PATH }}:$PATH"
          uv sync
      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Bump version and create tag
        id: bump_version
        run: |
          uv run commitizen bump --yes
          echo "NEW_VERSION=$(uv run commitizen version)" >> $GITHUB_OUTPUT
      - name: Push changes and tag
        run: |
          git push
          git push --tags
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.bump_version.outputs.NEW_VERSION }}
          name: v${{ steps.bump_version.outputs.NEW_VERSION }}
          generate_release_notes: true
          files: |
            CHANGELOG.md
